### ISSUE TITLE
Tasks

### ISSUE THREAD

**Issue by m-schuetz** [potree/PotreeConverter#430]
# Bugs/Issues to fix:

- [ ] Allow different point formats in input files. #428
- [ ] Compute new suitable scale and offset, if the ones from the input don't work. #421, #426
- [ ] Gracefully handle failure cases, e.g. severe "teapot in a stadium" scenarios. #427
    - [ ] Let users know that the input data should be sanitized before conversion. 
    - [ ] Print useful error messages if the input data is impossible to handle, e.g. hundreds of millions of points at the same position or a bounding box where 99% of the data fits into a single cell of a 512^3 grid.
- [ ] Improve handling of volume data. Used to crash, and with fix to crash it's still stuck forever. #427
- [ ] Make PotreeConverter automatically delete the tmpCunkRoots.bin file #430
